In [1]:
import pandas as pd
import numpy as np

In [2]:
df_all = pd.DataFrame(columns=['Category','Gender','Age','Year','Division','Population'])
for year in [2013,2014,2015,2016,2017]:
    raw = pd.read_csv("../raw_data/East Central Data/Movie Purchaser Behavior EC {}.csv".format(year),skiprows=1)
    df = pd.DataFrame(raw)
    
    df = df.dropna().drop(df.columns[[1, 2, 3]], axis=1)
    # print(df.head(3))
    # replace ' ' in category names with "_"
    cat = list(i.strip().replace(' ','_').lower() for i in list(df.iloc[:,0]))
    # print("{} cat: {}".format(year,cat))

    # population for each category
    pop_list = []
    for index, row in df.iterrows():
        pop_list += [int(row[5])] + [int(row[8])]\
                    + [int(row[11])] + [int(row[14])]\
                    + [int(row[17])]+ [int(row[6])]\
                    +  [int(row[9])] + [int(row[12])]\
                    + [int(row[15])]+ [int(row[18])]

    # clean data table
    clean_df = pd.DataFrame(columns=['Category','Gender','Age','Year','Division','Population'])
    cat_list = []
    for i in cat:
        cat_list += [i]*10
    clean_df["Category"] = cat_list
    clean_df['Gender'] = (['Male']*5+['Female']*5)*len(cat)
    clean_df['Age'] = ['28-24','25-34','35-44','45-54','55+']*2*len(cat)
    clean_df['Year'] = [year]*len(cat)*10
    clean_df['Division'] = ['Central East']*len(cat)*10
    clean_df['Population'] = pop_list
    df_all = pd.concat([df_all,clean_df], ignore_index=True)
    print ("finish {}".format(year))
df_all

finish 2013
finish 2014
finish 2015
finish 2016
finish 2017

,Category,Gender,Age,Year,Division,Population
0,totals,Male,28-24,2013,Central East,31
1,totals,Male,25-34,2013,Central East,51
2,totals,Male,35-44,2013,Central East,71
3,totals,Male,45-54,2013,Central East,64
4,totals,Male,55+,2013,Central East,78
5,totals,Female,28-24,2013,Central East,40
6,totals,Female,25-34,2013,Central East,73
7,totals,Female,35-44,2013,Central East,66
8,totals,Female,45-54,2013,Central East,101
9,totals,Female,55+,2013,Central East,127
10,video_game,Male,28-24,2013,Central East,26
11,video_game,Male,25-34,2013,Central East,37
12,video_game,Male,35-44,2013,Central East,49
13,video_game,Male,45-54,2013,Central East,31
14,video_game,Male,55+,2013,Central East,13
15,video_game,Female,28-24,2013,Central East,24
16,video_game,Female,25-34,2013,Central East,46
17,video_game,Female,35-44,2013,Central East,35
18,video_game,Female,45-54,2013,Central East,31
19,video_game,Female,55+,2013,Central East,32
20,tv,Male,28-24,2013,Central East,23
21,tv,Male,25-34,2013,Central East,38
22,tv,Male,35-44,2013,Central East,63
23,tv,Male,45-54,2013,Central East,62
24,tv,Male,55+,2013,Central East,72
25,tv,Female,28-24,2013,Central East,30
26,tv,Female,25-34,2013,Central East,65
27,tv,Female,35-44,2013,Central East,62
28,tv,Female,45-54,2013,Central East,96
29,tv,Female,55+,2013,Central East,120
...,...,...,...,...,...,...
540,tablet_owner,Male,28-24,2017,Central East,6
541,tablet_owner,Male,25-34,2017,Central East,14
542,tablet_owner,Male,35-44,2017,Central East,16
543,tablet_owner,Male,45-54,2017,Central East,11
544,tablet_owner,Male,55+,2017,Central East,7
545,tablet_owner,Female,28-24,2017,Central East,2
546,tablet_owner,Female,25-34,2017,Central East,17
547,tablet_owner,Female,35-44,2017,Central East,20
548,tablet_owner,Female,45-54,2017,Central East,11
549,tablet_owner,Female,55+,2017,Central East,13
550,all_live_theater/concerts/dance-attended_last_...,Male,28-24,2017,Central East,10
551,all_live_theater/concerts/dance-attended_last_...,Male,25-34,2017,Central East,7
552,all_live_theater/concerts/dance-attended_last_...,Male,35-44,2017,Central East,14
553,all_live_theater/concerts/dance-attended_last_...,Male,45-54,2017,Central East,12
554,all_live_theater/concerts/dance-attended_last_...,Male,55+,2017,Central East,8
555,all_live_theater/concerts/dance-attended_last_...,Female,28-24,2017,Central East,5
556,all_live_theater/concerts/dance-attended_last_...,Female,25-34,2017,Central East,14
557,all_live_theater/concerts/dance-attended_last_...,Female,35-44,2017,Central East,14
558,all_live_theater/concerts/dance-attended_last_...,Female,45-54,2017,Central East,9
559,all_live_theater/concerts/dance-attended_last_...,Female,55+,2017,Central East,8
560,social_media_[social_media_user],Male,28-24,2017,Central East,15
561,social_media_[social_media_user],Male,25-34,2017,Central East,22
562,social_media_[social_media_user],Male,35-44,2017,Central East,27
563,social_media_[social_media_user],Male,45-54,2017,Central East,14
564,social_media_[social_media_user],Male,55+,2017,Central East,16
565,social_media_[social_media_user],Female,28-24,2017,Central East,7
566,social_media_[social_media_user],Female,25-34,2017,Central East,29
567,social_media_[social_media_user],Female,35-44,2017,Central East,25
568,social_media_[social_media_user],Female,45-54,2017,Central East,17
569,social_media_[social_media_user],Female,55+,2017,Central East,14

In [3]:
df_all.to_csv('clean_all_year_EC_withCAT.csv', index = False)

In [5]:
# convert category names to index
cat_list = list(df_all.Category.unique())
cat_dict = dict(zip(cat_list,[str(i) for i in range(0,len(cat_list))]))
cat_dict

{'all_live_theater/concerts/dance-attended_last_12_months': '8',
 'digital_music': '10',
 'magazine': '4',
 'movie_goers': '5',
 'radio': '3',
 'social_media_[social_media_user]': '9',
 'streaming_video': '11',
 'supermarket_goer_last_4_weeks': '6',
 'tablet_owner': '7',
 'totals': '0',
 'tv': '2',
 'video_game': '1'}

In [6]:
for index, row in df_all.iterrows():
    row[0] = cat_dict[row[0]]

In [7]:
df_all.to_csv('clean_all_year_EC_withIndex.csv', index = False)